# Generated by Django 4.1.7 on 2023-02-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.IntegerField()),
                ('symbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('group', models.IntegerField()),
                ('atomic_mass', models.DecimalField(decimal_places=2, max_digits=8)),
                ('more_info', models.CharField(max_length=255)),
            ],
        ),
    ]
