# Generated by Django 4.1.7 on 2023-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='atomic_mass',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
